In [15]:
# números aleatórios

import numpy as np

#geração de números inteiros
#um número inteiro

x = np.random.randint(100)
#print (x)

#array de número inteiro

z = np.random.randint(100, size=10)
#print (z)

zbid = np.random.randint(100, size = (10, 20))
print (zbid)


[[92 31  6 88 20 71 13 46 67 92 79 29  4 38 93  8 23 85 32 21]
 [71 61 87 84 21 30 10 56 54 78 23 54 64 57 20 89 19 37 30 71]
 [16 39 35 31 99 38 68 86 22 60 60  7 85 91 26 67 97 77  6 67]
 [39 71 15 81 57 10 67 17 52 55 83 70  8 18 82 84 30 47 46 47]
 [46 69  2 66 86 60 62 78 80 48 73 87 52 72 22 59 57 48 34 51]
 [ 2 29 25 53 97 73 42 50 93  4  9 49 94 99  6 44 18 97 46 97]
 [ 2 63 77 19 10  4 11 26 44 42  1 89 15 73 26 36 77 61 16 48]
 [60 75 49 37 48 99 63 62 71 43  1 28 12 45 21 62 80 87 49 15]
 [68 21 33 71 16 75 75 86 97 75  7 30 31 25  5 24 47 52 92 94]
 [15 41 50 36 81 78 62 43 53 85 73 25 32 41 45 67 24 74 73 19]]


In [19]:
# geração de floats aleatórios

import numpy as np

#array unidimensional de floats de 0 a 1

a = np.random.rand(5)
#print (a)

#array bidimensional de floats

b = np.random.rand(3, 2)
print (b)



[[0.63730515 0.53670574]
 [0.22005469 0.37392393]
 [0.93039776 0.24752866]]


In [29]:
# sortear um aleatório de uma lista

import numpy as np

c = [10, 11, 12, 13]

#np.random.choice(c, size = (2,2))

#aleatório de uma sequência
seq = np.arange(0,11, 2)
print (seq)
print (np.random.choice(seq))



[ 0  2  4  6  8 10]
4


In [32]:

import numpy as np

np.random.normal(0, 1, size=(10, 10))


array([[-0.30733276, -0.58993019,  1.3569865 , -1.06229002,  1.29411519,
         0.0949977 , -0.18818642,  0.71036344, -2.41593602, -0.57386154],
       [ 0.03557208,  0.87004019,  0.08004117,  1.02896168,  0.22333796,
         1.27626025,  1.27361635,  1.52506589,  0.38171393,  0.71058172],
       [-1.30798755,  0.35945669, -0.53821221, -0.28180783, -0.72000933,
         1.28881398, -1.72688534, -0.44427288, -0.40488205, -0.6313788 ],
       [ 0.64530612, -0.9567736 , -1.08351645,  0.85696376, -0.61852716,
        -0.88164361, -0.60266483,  1.93806885, -1.64299891,  0.73249302],
       [-1.42016438, -0.62042811,  0.79674435,  0.13636055,  1.02866199,
        -1.04950855,  0.32014953,  0.02144751, -1.51075661,  0.12519311],
       [-0.49878295,  0.28631876,  0.06334256, -0.40257438, -0.55723325,
         0.46063529, -0.31026805,  0.10042923,  1.84769657,  0.93527826],
       [-0.24414157,  0.61943445, -0.04298065,  0.13892972,  0.78066396,
        -1.67387446,  0.27007764, -1.9049691 